name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          runtime: node@22
          cache: true
          install: false
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # 7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: 'style: apply lint fixes'
